services:
  # 1. Base de Datos
  db:
    image: postgres:15-alpine
    container_name: emerald_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: emerald_stock
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # Dejamos la DB solo local por seguridad, o podes usar la variable si queres acceder remoto
      - "${HOST_IP:-127.0.0.1}:5433:5432"

  # 2. Backend
  backend:
    build: ./backend
    container_name: emerald_backend
    restart: always
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      # CAMBIO CLAVE: Variable dinámica para la IP
      - "${HOST_IP:-127.0.0.1}:4001:8000"
    environment:
      DATABASE_URL: postgresql://admin:adminpassword@db:5432/emerald_stock
    depends_on:
      - db
    volumes:
      - ./backend:/app

  # 3. Frontend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: emerald_frontend
    restart: always
    ports:
      # CAMBIO CLAVE: Variable dinámica para la IP
      - "${HOST_IP:-127.0.0.1}:4000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # CAMBIO CRÍTICO 2:
      # Esto permite que en el servidor definas la IP real (ej: http://192.168.1.50:4001)
      # Si no, desde otra PC buscaría "localhost" y fallaría.
      - VITE_API_URL=${VITE_API_URL:-http://localhost:4001}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  # 4. PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: emerald_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@isp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      # CAMBIO CLAVE: Variable dinámica para la IP
      - "${HOST_IP:-127.0.0.1}:4002:80"
    depends_on:
      - db

volumes:
  postgres_data: