services:
  # 1. Base de Datos
  db:
    image: postgres:15-alpine
    container_name: emerald_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: emerald_stock
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # 2. Backend
  backend:
    build: ./backend
    container_name: emerald_backend
    restart: always
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "4001:8000" # <--- TU PUERTO ELEGIDO
    environment:
      DATABASE_URL: postgresql://admin:adminpassword@db:5432/emerald_stock
    depends_on:
      - db
    volumes:
      - ./backend:/app

  # 3. Frontend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: emerald_frontend
    restart: always
    ports:
      - "4000:5173" # TU PUERTO ELEGIDO
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # CORRECCIÓN CRÍTICA: Apuntamos al 4001 que es donde Docker expone tu API
      - VITE_API_URL=http://localhost:4001 
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  # 4. PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: emerald_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@isp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "4002:80"
    depends_on:
      - db

volumes:
  postgres_data: